import type { NextPage } from 'next'
import Head from 'next/head'

import SystemProvider from '@core/providers/systemProvider';
import PageSkeleton from '@core/providers/pageSkeleton';
import ProductsMainView from '@modules/products/Views/productsMainVew';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SystemProvider>
        <PageSkeleton>
          <ProductsMainView />
        </PageSkeleton>
      </SystemProvider>
    </>
  )
}

export default Home
